CREATE ROLE %I WITH
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  LOGIN
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT -1
  PASSWORD %L;

GRANT USAGE ON SCHEMA %I TO %I;
ALTER ROLE %I SET search_path TO %I, pg_temp;
